import 'package:math_buddy_v1/models/quiz_model.dart';

final List<QuizContent> kenalObjekQuiz = [
  QuizContent(
    id: '1',
    imagePaths: ['assets/quiz/kenal_objek/soalan 1.png'],
    optionA: 'WARNA BIRU',
    optionB: 'WARNA MERAH',
    correctAnswer: 'WARNA BIRU',
  ),
  QuizContent(
    id: '2',
    imagePaths: ['assets/quiz/kenal_objek/soalan 2.png'],
    optionA: 'SAIZ BESAR',
    optionB: 'SAIZ KECIL',
    correctAnswer: 'SAIZ KECIL',
  ),
  QuizContent(
    id: '3',
    imagePaths: ['assets/quiz/kenal_objek/soalan 3.png'],
    optionA: 'BENTUK SEGI TIGA',
    optionB: 'BENTUK SEGI EMPAT SAMA',
    correctAnswer: 'BENTUK SEGI TIGA',
  ),
  QuizContent(
    id: '4',
    imagePaths: ['assets/quiz/kenal_objek/soalan 4.png'],
    optionA: 'WARNA HIJAU',
    optionB: 'WARNA OREN',
    correctAnswer: 'WARNA OREN',
  ),
  QuizContent(
    id: '5',
    imagePaths: ['assets/quiz/kenal_objek/soalan 5.png'],
    optionA: 'BENTUK SEGI EMPAT TEPAT',
    optionB: 'BENTUK SEGI EMPAT SAMA',
    correctAnswer: 'BENTUK SEGI EMPAT TEPAT',
  ),
  QuizContent(
    id: '6',
    imagePaths: ['assets/quiz/kenal_objek/soalan 6.png'],
    optionA: 'WARNA MERAH',
    optionB: 'WARNA UNGU',
    correctAnswer: 'WARNA MERAH',
  ),
  QuizContent(
    id: '7',
    imagePaths: ['assets/quiz/kenal_objek/soalan 7.png'],
    optionA: 'SAIZ KECIL',
    optionB: 'SAIZ BESAR',
    correctAnswer: 'SAIZ BESAR',
  ),
  QuizContent(
    id: '8',
    imagePaths: ['assets/quiz/kenal_objek/soalan 8.png'],
    optionA: 'BENTUK BULAT',
    optionB: 'BENTUK SEGI TIGA',
    correctAnswer: 'BENTUK BULAT',
  ),
  QuizContent(
    id: '9',
    imagePaths: ['assets/quiz/kenal_objek/soalan 9.png'],
    optionA: 'WARNA KUNING',
    optionB: 'WARNA HITAM',
    correctAnswer: 'WARNA HITAM',
  ),
  QuizContent(
    id: '10',
    imagePaths: ['assets/quiz/kenal_objek/soalan 10.png'],
    optionA: 'BENTUK SEGI EMPAT SAMA',
    optionB: 'BENTUK SEGI EMPAT TEPAT',
    correctAnswer: 'BENTUK SEGI EMPAT SAMA',
  ),
  // Add up to 10
];

final List<QuizContent> susunNomborQuiz = [
  QuizContent(
    id: '1',
    imagePaths: ['assets/quiz/susun nombor/soalan 1.png'],
    optionA: 'SEMBILAN',
    optionB: 'SEPULUH',
    correctAnswer: 'SEMBILAN',
  ),
  QuizContent(
    id: '2',
    imagePaths: ['assets/quiz/susun nombor/soalan 2.png'],
    optionA: 'DUA',
    optionB: 'TIGA',
    correctAnswer: 'TIGA',
  ),
  QuizContent(
    id: '3',
    imagePaths: ['assets/quiz/susun nombor/soalan 3.png'],
    optionA: 'EMPAT',
    optionB: 'LIMA',
    correctAnswer: 'EMPAT',
  ),
  QuizContent(
    id: '4',
    imagePaths: ['assets/quiz/susun nombor/soalan 4.png'],
    optionA: '7',
    optionB: '6',
    correctAnswer: '6',
  ),
  QuizContent(
    id: '5',
    imagePaths: ['assets/quiz/susun nombor/soalan 5.png'],
    optionA: '1',
    optionB: '2',
    correctAnswer: '1',
  ),
  QuizContent(
    id: '6',
    imagePaths: ['assets/quiz/susun nombor/soalan 6.png'],
    optionA: '9',
    optionB: '8',
    correctAnswer: '8',
  ),
  QuizContent(
    id: '7',
    imagePaths: ['assets/quiz/susun nombor/soalan 7.png'],
    optionA: 'LIMA',
    optionB: 'EMPAT',
    correctAnswer: 'LIMA',
  ),
  QuizContent(
    id: '8',
    imagePaths: ['assets/quiz/susun nombor/soalan 8.png'],
    optionA: '2',
    optionB: '5',
    correctAnswer: '2',
  ),
  QuizContent(
    id: '9',
    imagePaths: ['assets/quiz/susun nombor/soalan 9.png'],
    optionA: '2',
    optionB: '6',
    correctAnswer: '6',
  ),
  QuizContent(
    id: '10',
    imagePaths: ['assets/quiz/susun nombor/soalan 10.png'],
    optionA: '2',
    optionB: '6',
    correctAnswer: '6',
  ),
  // Add up to 10
];

final List<QuizContent> tambahQuiz = [
  QuizContent(
    id: '1',
    imagePaths: ['assets/quiz/tambah/soalan - 1.png'],
    optionA: '3',
    optionB: '5',
    correctAnswer: '5',
  ),
  QuizContent(
    id: '2',
    imagePaths: ['assets/quiz/tambah/soalan - 2.png'],
    optionA: '8',
    optionB: '9',
    correctAnswer: '8',
  ),
  QuizContent(
    id: '3',
    imagePaths: ['assets/quiz/tambah/soalan - 3.png'],
    optionA: '3',
    optionB: '4',
    correctAnswer: '4',
  ),
  QuizContent(
    id: '4',
    imagePaths: ['assets/quiz/tambah/soalan - 4.png'],
    optionA: '7',
    optionB: '6',
    correctAnswer: '7',
  ),
  QuizContent(
    id: '5',
    imagePaths: ['assets/quiz/tambah/soalan - 5.png'],
    optionA: '10',
    optionB: '9',
    correctAnswer: '10',
  ),
  QuizContent(
    id: '6',
    imagePaths: ['assets/quiz/tambah/soalan - 6.png'],
    optionA: '2',
    optionB: '3',
    correctAnswer: '2',
  ),
  QuizContent(
    id: '7',
    imagePaths: ['assets/quiz/tambah/soalan - 7.png'],
    optionA: '8',
    optionB: '9',
    correctAnswer: '9',
  ),
  QuizContent(
    id: '8',
    imagePaths: ['assets/quiz/tambah/soalan - 8.png'],
    optionA: '5',
    optionB: '6',
    correctAnswer: '5',
  ),
  QuizContent(
    id: '9',
    imagePaths: ['assets/quiz/tambah/soalan - 9.png'],
    optionA: '2',
    optionB: '1',
    correctAnswer: '1',
  ),
  QuizContent(
    id: '10',
    imagePaths: ['assets/quiz/tambah/soalan - 10.png'],
    optionA: '3',
    optionB: '0',
    correctAnswer: '3',
  ),
];

final List<QuizContent> tolakQuiz = [
  QuizContent(
    id: '1',
    imagePaths: ['assets/quiz/tolak/soalan - 1.png'],
    optionA: '1',
    optionB: '5',
    correctAnswer: '1',
  ),
  QuizContent(
    id: '2',
    imagePaths: ['assets/quiz/tolak/soalan - 2.png'],
    optionA: '9',
    optionB: '3',
    correctAnswer: '3',
  ),
  QuizContent(
    id: '3',
    imagePaths: ['assets/quiz/tolak/soalan - 3.png'],
    optionA: '0',
    optionB: '6',
    correctAnswer: '0',
  ),
  QuizContent(
    id: '4',
    imagePaths: ['assets/quiz/tolak/soalan - 4.png'],
    optionA: '6',
    optionB: '7',
    correctAnswer: '7',
  ),
  QuizContent(
    id: '5',
    imagePaths: ['assets/quiz/tolak/soalan - 5.png'],
    optionA: '1',
    optionB: '2',
    correctAnswer: '2',
  ),
  QuizContent(
    id: '6',
    imagePaths: ['assets/quiz/tolak/soalan - 6.png'],
    optionA: '2',
    optionB: '3',
    correctAnswer: '2',
  ),
  QuizContent(
    id: '7',
    imagePaths: ['assets/quiz/tolak/soalan - 7.png'],
    optionA: '9',
    optionB: '8',
    correctAnswer: '8',
  ),
  QuizContent(
    id: '8',
    imagePaths: ['assets/quiz/tolak/soalan - 8.png'],
    optionA: '5',
    optionB: '6',
    correctAnswer: '6',
  ),
  QuizContent(
    id: '9',
    imagePaths: ['assets/quiz/tolak/soalan - 9.png'],
    optionA: '1',
    optionB: '0',
    correctAnswer: '1',
  ),
  QuizContent(
    id: '10',
    imagePaths: ['assets/quiz/tolak/soalan - 10.png'],
    optionA: '5',
    optionB: '6',
    correctAnswer: '6',
  ),
];

final List<QuizContent> masaQuiz = [
  QuizContent(
    id: '1',
    imagePaths: ['assets/quiz/masa/soalan 1.png'],
    optionA: 'SIANG',
    optionB: 'MALAM',
    correctAnswer: 'MALAM',
  ),
  QuizContent(
    id: '2',
    imagePaths: ['assets/quiz/masa/soalan 2.png'],
    optionA: 'PAGI',
    optionB: 'PETANG',
    correctAnswer: 'PAGI',
  ),
  QuizContent(
    id: '3',
    imagePaths: ['assets/quiz/masa/soalan 3.png'],
    optionA: 'PETANG',
    optionB: 'MALAM',
    correctAnswer: 'PETANG',
  ),
  QuizContent(
    id: '4',
    imagePaths: ['assets/quiz/masa/soalan 4.png'],
    optionA: 'ISNIN',
    optionB: 'SABTU',
    correctAnswer: 'SABTU',
  ),
  QuizContent(
    id: '5',
    imagePaths: ['assets/quiz/masa/soalan 5.png'],
    optionA: 'JUMAAT',
    optionB: 'AHAD',
    correctAnswer: 'JUMAAT',
  ),
];

final List<QuizContent> wangQuiz = [
  QuizContent(
    id: '1',
    imagePaths: ['assets/quiz/wang/soalan - 1.png'],
    optionA: 'SEPULUH RINGGIT',
    optionB: 'LIMA RINGGIT',
    correctAnswer: 'LIMA RINGGIT',
  ),
  QuizContent(
    id: '2',
    imagePaths: ['assets/quiz/wang/soalan - 2.png'],
    optionA: 'LIMA PULUH SEN',
    optionB: 'DUA PULUH SEN',
    correctAnswer: 'DUA PULUH SEN',
  ),
  QuizContent(
    id: '3',
    imagePaths: ['assets/quiz/wang/soalan - 3.png'],
    optionA: 'SERATUS RINGGIT',
    optionB: 'SEPULUH RINGIT',
    correctAnswer: 'SERATUS RINGGIT',
  ),
  QuizContent(
    id: '4',
    imagePaths: ['assets/quiz/wang/soalan - 4.png'],
    optionA: 'DUA PULUH SEN',
    optionB: 'SEPULUH SEN',
    correctAnswer: 'SEPULUH SEN',
  ),
  QuizContent(
    id: '5',
    imagePaths: ['assets/quiz/wang/soalan - 5.png'],
    optionA: 'SERINGGIT',
    optionB: 'DUA RINGGIT',
    correctAnswer: 'SERINGGIT',
  ),
  QuizContent(
    id: '6',
    imagePaths: ['assets/quiz/wang/soalan - 6.png'],
    optionA: 'RM 5.00',
    optionB: 'RM 6.00',
    correctAnswer: 'RM 6.00',
  ),
  QuizContent(
    id: '7',
    imagePaths: ['assets/quiz/wang/soalan - 7.png'],
    optionA: 'RM 10.00',
    optionB: 'RM 9.00',
    correctAnswer: 'RM 9.00',
  ),
  QuizContent(
    id: '8',
    imagePaths: ['assets/quiz/wang/soalan - 8.png'],
    optionA: 'RM 11.00',
    optionB: 'RM 10.00',
    correctAnswer: 'RM 11.00',
  ),
  QuizContent(
    id: '9',
    imagePaths: ['assets/quiz/wang/soalan - 9.png'],
    optionA: 'RM 5.00',
    optionB: 'RM 6.00',
    correctAnswer: 'RM 5.00',
  ),
];
