// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_adhKzqa7sXFrUrCIJcUX3lHTrsCkIBY',
    appId: '1:203773234403:web:2f73614e997bf0efd109d6',
    messagingSenderId: '203773234403',
    projectId: 'mathbuddy-v1',
    authDomain: 'mathbuddy-v1.firebaseapp.com',
    storageBucket: 'mathbuddy-v1.firebasestorage.app',
    measurementId: 'G-W3JKJPJKJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOw1rEwXaTfwSV8FtRRloQKMtRgGdchxM',
    appId: '1:203773234403:android:fd3c1205e9d25621d109d6',
    messagingSenderId: '203773234403',
    projectId: 'mathbuddy-v1',
    storageBucket: 'mathbuddy-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi05GurrKwgscyeCRdiU6Y7vspD4oH-IE',
    appId: '1:203773234403:ios:7ffee371d8c14c11d109d6',
    messagingSenderId: '203773234403',
    projectId: 'mathbuddy-v1',
    storageBucket: 'mathbuddy-v1.firebasestorage.app',
    iosBundleId: 'com.example.mathBuddyV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_adhKzqa7sXFrUrCIJcUX3lHTrsCkIBY',
    appId: '1:203773234403:web:59960002333fa463d109d6',
    messagingSenderId: '203773234403',
    projectId: 'mathbuddy-v1',
    authDomain: 'mathbuddy-v1.firebaseapp.com',
    storageBucket: 'mathbuddy-v1.firebasestorage.app',
    measurementId: 'G-NTTG953BTG',
  );
}
